micronaut:
    application:
        name: api

    server:
        cors:
            enabled: true

datasources:
    default:
        url: 'jdbc:postgresql://localhost:5432/carbonite'
        username: 'carbonite'
        password: 'carbonite'
        driverClassName: 'org.postgresql.Driver'

flyway:
    datasources:
        default:
            locations: classpath:migration