== Configuration

The most important part of a Carbon script is the configuration. The
configuration is declared as a variable called *carbon*. The
information found in that variable is used to build the Carbon script.

[source, groovy]
.configuration elements
----
carbon = [
   name: 'Script name',                // <1>
   version: '0.1.0',                   // <2>
   description: 'Script description',  // <3>
   options: [:],                       // <4>
   params: [:]                         // <5>
   configuration: '/path/to/external-configuration.groovy' // <6>
]
----

<1> Name of the script
<2> Current version of the script
<3> A description describing what the script is about
<4> Script options
<5> Script parameters
<6> External configuration

=== Basic properties

The basic properties of a Carbon script are:

- name
- version
- description

These properties are supposed to be required. This tries to force the
developer to at least say what the script is about, and what is the
current version of the script.

=== Options & Parameters

Following Picocli's explanation about options and parameters:

"Command line arguments can be separated into options and positional
parameters. Options have a name, positional parameters are usually the
values that follow the options, but they may be mixed."
-- Picocli 'Options and Parameters' section

==== Options

Options have a name, and normally are used to modify somehow the
behavior or the output of the script. Some examples are:

[source, shell]
----
hello-world --help       // shows hello-world help
show-stocks --refresh 5  // refresh stocks every 5 seconds
migrate --from a --to b  // migrates table a to table b
backup --verbose         // executes backup logging everything
----

===== Required

If you declare an option as *required* if it didn't have value the
script will show an error and the usage output.

[source, groovy]
----
include::{examples}/files/sync.groovy[indent=0]
----

In this example the *from* and *to* options are required. If we do not
provide values for them we'll get the following output:

[source, shell]
----
args: []
Missing required options [--from=<from>, --to=<to>]
Usage: sync [-hV] -f=<from> [-i=<interval>] -t=<to>
Copies new files from source dir to destination dir
  -f, --from=<from>   Source directory
  -h, --help          Show this help message and exit.
  -i, --interval=<interval>
                      Seconds to wait
  -t, --to=<to>       Destination directory
  -V, --version       Print version information and exit.
----

It's telling you that both options are missing.

===== Default value

For instance, lets create a script showing us the current date:

[source, groovy]
----
include::{examples}/datetime/datetime.groovy[indent=0]
----

<1> The key of the map entry is the name of the parameter
<2> *type*: The type of the parameter
<3> *description*: What is the parameter for
<4> *defaultValue*: If the user doesn't provide any. In this case we
include the default value in the description
<5> Then you can use the *format* parameter in your code

IMPORTANT: Notice that in the option description when including the
default value we're using simple quotes. *${DEFAULT-VALUE}* doesn't
exists in the script. The description string is used as a template by
Picocli when rendering the description.

If you execute:

[source, shell]
----
groovy datetime.groovy --help
----

You can see the options in the help output:

[source, shell]
----
Usage: datetime [-hV] [-f=<format>]
shows current date with the format
  -f, --format=<format>   Date format (dd/MM/yyyy HH:mm:ss)
  -h, --help              Show this help message and exit.
  -V, --version           Print version information and exit.
----

Now that we know the available options lets get the current time with
a custom format:

[source, shell]
.datetime with day and month
----
[user@host]$ groovy datetime.groovy --format dd/MM
08/02
----

==== Parameters

There're multiple scripts operating over the files passed as
parameters. For instance you may want to hash a given set of files in
order to make sure they haven't been tampered. Such script may well
look like this:

[source, groovy]
----
include::{examples}/files/hash-files.groovy[indent=0]
----

<1> The script is declaring a parameter named *files* which has arity
*1* meaning all parameters from position 1 are files considered to be
hashed.

In general parameters in Carbon should be a new map entry in the

[source, groovy]
----
carbon = [
    params: [
       name: [
           type: String,        // <1>
           arity: "1",          // <2>
           description: "",     // <3>
           paramLabel: "NAME"   // <4>
       ]
    ]
]
----

=== External configuration

At some point your script configuration maybe be a little bit bigger
than you expected.

[source, groovy]
.Script with configuration
-----
include::{examples}/configuration/sync_big.groovy[indent=0]
-----

There're more lines about configuration than the task we try to
achieve. It's a lot of noise. Wouldn't be nice to move all that
configuration stuff somewhere else ? What about this:

[source, groovy]
.script with external configuration
----
include::{examples}/configuration/sync.groovy[indent=0]
----

<1> Path to Carbon configuration

Perfect! Now we can see clearly the script is doing, and move all the
script related configuration to another file:

[source, groovy]
.sync_config.groovy
----
include::{examples}/configuration/sync_config.groovy[indent=0]
----

It's important to notice that whereas when adding the carbon
configuration within the same script requires to use the *carbon*
variable and use a map object, when using an external configuration
file, all configuration properties should appear outside the carbon
variable.

[source, groovy]
.included in script
----
carbon = [
 name: '',
 description: ''
]
----

[source, groovy]
.external config
----
name = ''
description = ''
----

=== Access from code

When externalizing Carbon script's configuration to another file, you
can access configuration as a map from your script.